version: '3.8'
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=*******************************   
      - DEBUG=1
      - EMAIL_HOST_USER=******************
      - EMAIL_HOST_PASSWORD=*******************
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_
      - STRIPE_TEST_SECRET_KEY=sk_test_
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
